"""edit Task table - add not nullable value in is_finished #2

Revision ID: 3b0573ab0a27
Revises: 5f12207036ae
Create Date: 2023-03-30 12:52:46.533167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0573ab0a27'
down_revision = '5f12207036ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
