"""edit Task table - add not nullable value in is_finished

Revision ID: 5f12207036ae
Revises: 755901ecb852
Create Date: 2023-03-30 12:47:56.078707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f12207036ae'
down_revision = '755901ecb852'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
