"""edit Task table - add not nullable value in is_finished #3

Revision ID: a9451ebef2dc
Revises: 3b0573ab0a27
Create Date: 2023-03-30 12:53:53.903217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9451ebef2dc'
down_revision = '3b0573ab0a27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
